-- Generated by scripts/build_seed_sql.py from scripts/activity_definitions.py. Do not edit by hand.

INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_SEASON', 'CS_SEASON', 'Season', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_CROPPING_SYSTEM', 'CS_CROPPING_SYSTEM', 'Cropping system', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_LAND_PREPARATION', 'CS_LAND_PREPARATION', 'Land preparation method', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_IRRIGATION_SOURCE', 'CS_IRRIGATION_SOURCE', 'Irrigation source', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_IRRIGATION_METHOD', 'CS_IRRIGATION_METHOD', 'Irrigation method', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_SEED_TYPE', 'CS_SEED_TYPE', 'Seed type', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_SEED_SOURCE', 'CS_SEED_SOURCE', 'Seed source', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_SOWING_METHOD', 'CS_SOWING_METHOD', 'Sowing method', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_FERTILIZER_TYPE', 'CS_FERTILIZER_TYPE', 'Fertiliser type', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_MACHINERY', 'CS_MACHINERY', 'Machinery', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_GROWTH_STAGE', 'CS_GROWTH_STAGE', 'Growth stage', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_CROP_CONDITION', 'CS_CROP_CONDITION', 'Crop condition', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_INFESTATION_TYPE', 'CS_INFESTATION_TYPE', 'Infestation type', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_INFESTATION_AGENT', 'CS_INFESTATION_AGENT', 'Pest, disease or weed', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_SEVERITY', 'CS_SEVERITY', 'Severity', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_CONTROL_ACTION', 'CS_CONTROL_ACTION', 'Action taken', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_DAMAGE_CAUSE', 'CS_DAMAGE_CAUSE', 'Damage cause', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_AGRO_ECOLOGICAL_ZONE', 'CS_AGRO_ECOLOGICAL_ZONE', 'Agro-ecological zone', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
INSERT INTO "public"."g2p_attributes" ("attribute_id", "attribute_code", "attribute_display", "is_hierarchical") VALUES ('CS_SEED_VARIETY', 'CS_SEED_VARIETY', 'Seed variety', FALSE)
  ON CONFLICT (attribute_id) DO UPDATE SET "attribute_code" = EXCLUDED."attribute_code", "attribute_display" = EXCLUDED."attribute_display", "is_hierarchical" = EXCLUDED."is_hierarchical";
