#!/usr/bin/env python3
"""Generate the Crop Sown Registry seed SQL from scripts/activity_definitions.py.

    python3 scripts/build_seed_sql.py          # write the SQL files
    python3 scripts/build_seed_sql.py --check  # fail if the committed SQL is stale

Every statement is an upsert, so db-seed can re-run on each helm upgrade.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import activity_definitions as d  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
META = ROOT / "crop-sown-extension/src/openg2p_registry_crop_sown_extension/meta_data"


def q(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (dict, list)):
        return "CAST(" + q(json.dumps(value, ensure_ascii=False, separators=(",", ":"))) + " AS JSONB)"
    return "'" + str(value).replace("'", "''") + "'"


def upsert(table: str, row: dict, conflict: str) -> str:
    columns = ", ".join(f'"{c}"' for c in row)
    values = ", ".join(q(v) for v in row.values())
    keys = {c.strip() for c in conflict.split(",")}
    updates = ", ".join(f'"{c}" = EXCLUDED."{c}"' for c in row if c not in keys)
    return f'INSERT INTO "public"."{table}" ({columns}) VALUES ({values})\n  ON CONFLICT ({conflict}) DO UPDATE SET {updates};\n'


HEADER = "-- Generated by scripts/build_seed_sql.py from scripts/activity_definitions.py. Do not edit by hand.\n\n"


def activity_types_sql() -> str:
    out = [HEADER]
    for index, t in enumerate(d.ACTIVITY_TYPES, start=1):
        row = {
            "activity_type_id": f"c5000000-0000-4000-8000-0000000001{index:02d}",
            "register_id": d.REGISTER_ID,
            "activity_type": t["activity_type"],
            "display_name": t["display_name"],
            "description": t.get("description"),
            "display_order": t.get("display_order"),
            "is_active": True,
            "payload_schema": t["payload_schema"],
            "section_ui_schema": t.get("section_ui_schema"),
            "requires_context": t.get("requires_context", True),
            "is_repeatable": t.get("is_repeatable", True),
            "uniqueness_fields": t.get("uniqueness_fields"),
            "requires_prior_types": t.get("requires_prior_types"),
            "sequence_enforcement": t.get("sequence_enforcement", "WARN"),
            "due_rule": t.get("due_rule"),
            "max_backdate_days": t.get("max_backdate_days"),
            "allow_future_dated": t.get("allow_future_dated", False),
            "requires_verification": t.get("requires_verification", False),
            "reference_rules": t.get("reference_rules"),
            "ethiopian_date_fields": t.get("ethiopian_date_fields"),
        }
        out.append(upsert("g2p_activity_types", row, "register_id, activity_type"))
    return "".join(out)


def register_sql() -> str:
    row = {
        "register_id": d.REGISTER_ID,
        "register_mnemonic": d.REGISTER_MNEMONIC,
        "register_subject": "Crop seasons",
        "register_description": "Crop Sown Registry: what farmers plan, sow, observe and harvest",
        "master_register_id": None,
        "register_rank": 1,
        "functional_id_generation_required": False,
        "register_purpose": "ACTIVITY",
        "has_image": False,
        "dedup_is_enabled": False,
        "completion_score_required": False,
        "outgest_applicable": False,
        "requires_registrant_authentication": False,
    }
    return HEADER + upsert("g2p_register_definitions", row, "register_id")


def indicators_sql() -> str:
    out = [HEADER]
    for index, (code, name, unit, definition, order) in enumerate(d.INDICATORS, start=1):
        out.append(upsert("g2p_activity_indicators", {
            "indicator_id": f"c5000000-0000-4000-8000-0000000002{index:02d}", "register_id": d.REGISTER_ID,
            "indicator_code": code, "display_name": name, "unit": unit, "definition": definition,
            "display_order": order, "is_active": True, "description": None,
        }, "register_id, indicator_code"))
    return "".join(out)


def odk_sql() -> str:
    out = [HEADER, "-- Forms stay inactive until an environment sets odk_project_id and is_active.\n"]
    for form in d.ODK_FORMS:
        row = {**form, "register_id": d.REGISTER_ID, "submissions_pulled": 0, "submissions_failed": 0}
        # Never reset a live cursor or activation on re-seed: insert only.
        columns = ", ".join(f'"{c}"' for c in row)
        values = ", ".join(q(v) for v in row.values())
        out.append(f'INSERT INTO "public"."g2p_activity_odk_forms" ({columns}) VALUES ({values})\n'
                   '  ON CONFLICT (odk_project_id, odk_form_id) DO UPDATE SET "mapping" = EXCLUDED."mapping";\n')
    return "".join(out)


def outputs() -> dict[Path, str]:
    # No code lists: they live in Master Data (ETH pack, agriculture domain) and
    # the platform reads them there.
    return {
        META / "register-metadata/g2p_register_definitions.sql": register_sql(),
        META / "activity-metadata/10_g2p_activity_types.sql": activity_types_sql(),
        META / "activity-metadata/20_g2p_activity_indicators.sql": indicators_sql(),
        META / "activity-metadata/30_g2p_activity_odk_forms.sql": odk_sql(),
    }


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, content in outputs().items():
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Seed SQL is stale; run scripts/build_seed_sql.py:\n  " + "\n  ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
